version: "3.7"

networks:
  localnetwork:
    name: localnetwork

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "14333:1433"
    volumes:
      - ./MSSQLscripts/:/scripts/
    environment:
      SA_PASSWORD: "P@55W0RD"
      ACCEPT_EULA: "Y"
    command:
      
      - /bin/bash
      - -c
      - |
        #Launch MSSQL and send to background
        /opt/mssql/bin/sqlservr &
        #Wait 180 sec fot it to be available
        sleep 180
        #run script
        /opt/mssql-tools/bin/sqlcmd -U sa -P $${SA_PASSWORD} -l 30 -e -i ./scripts/createMVCTuincentrum.sql
        sleep infinity
    networks:
      - localnetwork

  website:
    build: ./MVCTuinCentrumCore
    depends_on: 
      - sql-server-db
    ports:
      - "8080:80"
    networks:
      - localnetwork